---
sudo: required
services: docker

env:
  - distro: ubuntu1404
  - distro: ubuntu1604
  - distro: centos7

script:
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/djx339/4c0b0040e3b1d65810dbbd80c318a290/raw/
  - chmod +x ${PWD}/tests/test.sh

  - chmod +x ${PWD}/tests/travis_test.sh
  - ${PWD}/tests/travis_test.sh

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
